/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_ulez_vad_2_PcmSplite */

#ifndef _Included_com_github_ulez_vad_2_PcmSplite
#define _Included_com_github_ulez_vad_2_PcmSplite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_ulez_vad_2_PcmSplite
 * Method:    j2cSplitePCM
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_ulez_vad_12_PcmSplite_j2cSplitePCM
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
